### PR TITLE
Fix/bipolar center color

### LINKED ISSUE #60: Fix knob background light for parameters that have a range like -100 to 100 (as opposed to 0 to 100).
### Feature Description

Knob backgrounds are coloured from green (0) to red (100) depending on their value. This works well for values that go from 0 to 100 (for example) where values closer to 0 mean "very little" and values closer to 100 mean "a lot". Some parameters work differently though, panning goes from -100 to 100, and its "balanced" position is 0. For panning -100 should be red, 0 should be green and 100 should be red again.

### Level

Image

Image

Image

### Panning

The curve is the same as it is for level:

Image

Image

Image

Image

But ideally here we want:
- -100 red
- -75 orange
- 0 green
- 75 orange
- 100 red

### Motivation / Use Case

It's a small touch to make the UI nicer

### Alternatives Considered

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by hemanth5055**
### 📌 Description

This PR fixes the knob background color logic for parameters with **ranges that span negative to positive values** (e.g., `-100 to 100`).

* Previously, the knob background worked only for `0 → 100` ranges (green → red).
* For bipolar ranges like `-100 → 100`, the midpoint (`0`) should represent balance and display as **green**, while extremes (`-100` and `100`) should display as **red**.
* Added a gradient mapping for negative, zero, and positive values:

  * `-100 → red`
  * `-75 → orange`
  * `0 → green`
  * `+75 → orange`
  * `+100 → red`

---

### ✅ Related Issue

Closes #60 

---

#### Before

Knob background incorrectly mapped `0 → green` and `100 → red`, but did not account for `-100 → 100` ranges.

#### After

Knob background now correctly displays **red at extremes, green at center, orange in between** for bipolar ranges.

https://github.com/user-attachments/assets/db734ca7-c2a7-4176-b495-9b578736279d

---

### ⚠️ Breaking Changes

* None. The fix only updates knob UI behavior for parameters with bipolar ranges.

---

### 🔍 Testing Done

* Verified knob color behavior with `0 → 100` ranges (unchanged).
* Verified knob color behavior with `-100 → 100` ranges (now correct).
* Manually tested with parameters like **panning**.

---

### ℹ️ Additional Notes

* Improves UI intuitiveness and clarity for parameters with bipolar ranges.
* Small but impactful UX improvement.

### CODE REVIEW

File: view/src/components/elements/knob/Knob.tsx [hunk 1]
```diff
@@ -15,13 +15,53 @@ const interpolateColor = (
   return `rgb(${r}, ${g}, ${b})`;
 };
 
+const green: [number, number, number] = [170, 255, 170];
+const orange: [number, number, number] = [255, 200, 0];
```
Comment (lilyvanoekel) [inline view/src/components/elements/knob/Knob.tsx:19]: We don't need `orange` as a specified colour, we can just rely on the blending between green and red. (I can see how that was confusing in the issue description, sorry about that!)

**Comment by lilyvanoekel** [comment]
@hemanth5055 thanks for this PR! I had a few small comments.

I also have a question about the video. It seems like the velocity knob also changes background colour?

**Review by lilyvanoekel — APPROVED** [review]
